// <auto-generated />
namespace FacsalData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Fakie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fakie));
        
        string IMigrationMetadata.Id
        {
            get { return "201406031826274_Fakie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
